### ISSUE TITLE
update issues due to illegal characters in URL

### ISSUE THREAD

**Issue by andreasbaumann** [Eurospider/zhlex#1]
```
2016-10-06 03:22:38,165 INFO - Downloading http://www2.zhlex.zh.ch/Appl/zhlex_r.nsf/0/24AE639BC42E64B7C1257815002BC6C0/$file/631.55_ 29.11.99_27.pdf 
2016-10-06 03:22:38,167 ERROR - fetcher failed 
java.lang.IllegalArgumentException
        at java.net.URI.create(URI.java:859)
        at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:69)
        at com.eurospider.zhlex.HttpUtilities.issueGetRequest(HttpUtilities.java:131)
        at com.eurospider.zhlex.HttpUtilities.getContentAsStream(HttpUtilities.java:119)
        at com.eurospider.zhlex.HttpUtilities.saveToFile(HttpUtilities.java:105)
        at com.eurospider.zhlex.ZHLexFetcher.fetch(ZHLexFetcher.java:117)
        at com.eurospider.zhlex.ZHLexFetcher.processFolder(ZHLexFetcher.java:197)
        at com.eurospider.zhlex.ZHLexFetcher.download(ZHLexFetcher.java:418)
        at com.eurospider.zhlex.ZHLexFetcher.main(ZHLexFetcher.java:613)
Caused by: java.net.URISyntaxException: Illegal character in path at index 89: http://www2.zhlex.zh.ch/Appl/zhlex_r.nsf/0/24AE639BC42E64B7C1257815002BC6C0/$file/631.55_ 29.11.99_27.pdf
        at java.net.URI$Parser.fail(URI.java:2825)
        at java.net.URI$Parser.checkChars(URI.java:2998)
        at java.net.URI$Parser.parseHierarchical(URI.java:3082)
        at java.net.URI$Parser.parse(URI.java:3030)
        at java.net.URI.<init>(URI.java:595)
        at java.net.URI.create(URI.java:857)
        ... 8 more
```

**Comment by andreasbaumann** [comment]
`631.55_ 29.11` unescaped space, should be %20.

**Comment by andreasbaumann** [comment]
Verified and updated.
